package com.capg.soapmain;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2018-07-30T23:46:58.857+05:30
 * Generated source version: 3.2.5
 *
 */
@WebService(targetNamespace = "http://soapMain.capg.com", name = "SoapMainService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SoapMainService {

    @WebMethod
    @WebResult(name = "getDetailsResponse", targetNamespace = "http://soapMain.capg.com", partName = "parameters")
    public GetDetailsResponse getDetails(
        @WebParam(partName = "getDetails", name = "getDetails", targetNamespace = "http://soapMain.capg.com")
        GetDetails getDetails,
        @WebParam(partName = "InputHeader", name = "getDetailsHeader", targetNamespace = "http://soapMain.capg.com", header = true)
        GetDetailsHeader inputHeader
    );
}
